modLoader="javafml" #mandatory
loaderVersion="[1,)"
license="CC-BY-NC-4.0"
issueTrackerURL="https://github.com/${github}/issues"
[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${version}" #mandatory
displayName="${mod_name}" #mandatory
displayURL="https://github.com/${github}" #optional
logoFile="icon.png" #optional
credits="${credits}" #optional
authors="${mod_author}" #optional
description='''${mod_description}'''
[[dependencies.tm_armory]] #optional
   modId="neoforge" #mandatory
   mandatory=true #mandatory
   versionRange="[1,)" #mandatory
   ordering="NONE"
   side="BOTH"
[[dependencies.tm_armory]]
   modId="minecraft"
   mandatory=true
versionRange="${minecraft_version_range}"
   ordering="NONE"
   side="BOTH"
[[dependencies.tm_armory]]
   modId="miapi"
   mandatory=true
   versionRange="[${miapi_version},)"
   ordering="NONE"
   side="BOTH"
